services:
  db:
    image: postgres:16
    container_name: valuation_ops_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: valuation_ops
      POSTGRES_USER: valuation_user
      POSTGRES_PASSWORD: supersecretpassword   # change later
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
